config/routes.rb
Rails.application.routes.draw do

  # New way user registration
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "(/:user)/sign_up/(:affiliate)" => "users/registrations#new", as: "new_user_registration"
    get "/:id/sign_out" => "devise/sessions#destroy"
  end


  authenticated :user, ->(u) { u.role == 'admin' } do
    root to: "users/visits#index", as: :admin_root
    namespace :users do
      resources :visits
    end
  end

  get "admin/week_percentages", to: 'admin#week_percentages', as: 'admin_week_percentages'
  get "admin/index", to: 'admin#index', as: 'admin_index'

  # for affiliates investors dashboard
  namespace :users do
    resources :users_investments, except: [:edit, :update]
    resources :affiliates
    resources :campaigns
  end

  # New way user registrations
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users do
    resources :investmentss
    resources :wallets
    get 'wallets/show'
  end

  resources :wallets, only: [:show] do
    resources :transactions, only: [:new, :create, :destroy]
    resources :users do
      resources :transactions, only: [:new, :create, :destroy]
    end
  end

  resources :transactions, only: [:index, :edit, :update, :show]
  resources :deposits, only: [:index, :edit, :update, :show]
  post "preset_investment", to: "investments#preset_investment", as: :preset_investment
  resources :investments do
    resources :payouts, only: [:index]
  end

  # Investment create
  post "investment/get_end_date", to: "investments#get_end_date"
  post "investment/get_frequency", to: "investments#get_frequency"
  post "investment/expected_return", to: "investments#expected_return"
  post "investment/get_range", to: "investments#get_range"
  post "investment/get_payment_method_id", to: "investments#get_payment_method_id"
  post "investment/confirm", to: "investments#confirm"
  post "investment/get_edit_investment", to: "investments#get_edit_investment"
  post "investment/get_frequency_title", to: "investments#get_frequency_title"
  post "investment/get_status", to: "investments#get_status"

  get :certificate, to: "investments#certificate"
  resources :week_percentages
  resources :payouts, only: [:index, :show]

  resources :dashboards, only: [:index]

  resources :performance, ohly: [:index]
  post "performance/chartdata", to: "performance#chartdata"
  # Admin user profile update
  get "profile/:id/edit", to: "profiles#edit", as: :edit_user_profile
  patch "profiles/:id", to: "profiles#update", as: :update_user_profile
  post "profiles/:id", to: "profiles#update"
  put "profiles/:id", to: "profiles#update"
  post "profile/password_update/:id", to: "profiles#password_update", as: :password_update_user_profile
  #put "profile/password_update/:id", to: "profiles#password_update", as: :password_update_user_profile

  get "support", to: "profiles#edit", as: :contact_support
  get "free_coins", to: "profile#edit", as: :free_coins

  # Profiles
  get "profile/edit", to: "profiles#edit", as: :edit_profile
  get 'profile/auth_factor', to: "profiles#auth_factor", as: :auth_factor
  get 'profile/enable_two_factor', to: "profiles#enable_two_factor", as: :enable_two_factor
  get 'profile/resend_otp', to: "profiles#resend_otp", as: :resend_otp

  # Phone Verification
  post "profile/send_phone_verification", to: "profiles#send_phone_verification"
  post "profile/verify_phone", to: "profiles#verify_phone"
  post "profile/resend_code", to: "profiles#send_phone_verification"
  #patch "profile/update", to: "profiles#update", as: :update_profile
  get "profiles", to: "profiles#index", as: :proifles
  post "profile/update", to: "profiles#update", as: :update_profile
  post "profile/password_update", to: "profiles#password_update", as: :password_update_profile
  delete "profile", to: "profiles#destroy", as: :profile_destroy

  # Phone Numbers
  resources :phone_numbers, only: [:create, :destroy]
  resources :number_verifications, only: [:new, :create]

  # admin user add phone number
  post "phone_numbers/:id", to: "phone_numbers#create", as: :user_phone_number
  delete "phone_numners", to: "phone_numbers#destory", as: :destroy_user_phone_number

  # Payments
  get 'payments_all', to: "payments#index", as: :payments_all
  get "payment/:id/show", to: "payments#show", as: :payment_show
  get 'payments', to: "payments#create"
  get 'payments/:id/address/:coin', to: "payments#address", as: :payment_address
  get 'payment/:id/status', to: "payments#status", as: :payment_status
  post 'payment/:id/callback', to: "payments#callback", as: :payment_callback
  post 'payments/:id/callback', to: "payments#callback", as: :payments_callback

  # routes for ajax calls
  match 'expected_return', to: "expected_return#earning", as: :expected_return, via: :post
  match 'expected_return_25', to: "expected_return#per_month_25", as: :expected_return_25, via: :post
  match 'currency_converter', to: "currency_converter#convert", as: :currency_converter, via: :get
  match 'currency_in_crypto', to: "currency_converter#show_crypto", as: :currency_in_crypto, via: :get

  # Wizard Investment
  resource :investment do
    get :name
    get :timeframe
    post :validate_step
  end
  resource :wizard_investment do
    get :start
    get :plan
    get :name
    get :timeframe
    get :payout
    get :amount
    get :payment
    get :review
    get :pay
    get :cancel
    get :ready
    get :continue
    get :return_expected_return_value

    post :validate_step
  end

  root 'dashboards#index'

  # APIs
  mount API::Base, at: '/'
  mount GrapeSwaggerRails::Engine, at: '/documentation'
end

app/controllers/wizard_investments_controller.rb
class WizardInvestmentsController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!

  before_action :load_investment_wizard, except: %i(validate_step cancel ready continue pay)
  before_action :set_investment_plans
  before_action :set_payout_frequency
  before_action :set_payment_method

  def validate_step
    current_step = params[:current_step]


    @investment_wizard = wizard_investment_for_step(current_step)
    @investment_wizard.investment.attributes = investment_wizard_params

    binding.pry
    if @investment_wizard.investment[:user_id].nil?
      @investment_wizard.investment.write_attribute("user_id",current_user.id)
    end

    if current_step == "amount"

      # PLANS HAS BEEN REMOVED
      # Upgrade plan if user invest more money that in plan range
      #amount = params[:investment_wizard][:invested_amount].to_f
      #if amount_incurrency(amount) > @investment_wizard.investment.investment_plan.max
        #new_invested_amount = InvestmentPlan.where("max > ?", amount_incurrency(amount).to_f).first
        #@investment_wizard.investment.write_attribute("investment_plan_id", new_invested_amount.id)
      #end

      # TODO remove associaltion of investment plan in future
      @investment_wizard.investment.write_attribute("investment_plan_id", InvestmentPlan.first.id)
      @investment_wizard.investment.write_attribute("earned", 0.0)

      # invested_attributes, payment_frequency
      expected = ExpectedReturn.new(
        @investment_wizard.investment.attributes,
        @investment_wizard.investment.payout_frequency.name,
        current_user
      )
      #binding.pry

      @investment_wizard.investment.write_attribute("expected_return",expected.amount)
      @investment_wizard.investment.write_attribute("investment_earning",expected.return_25)
      @investment_wizard.investment.write_attribute("currency",@currency.downcase)
    end

    if params[:investment_wizard][:timeframe].present?
      timeframe = params[:investment_wizard][:timeframe].to_i
      @investment_wizard.investment.write_attribute("end_date", Time.now.months_since(timeframe))
    end
    session[:investment_attributes] = @investment_wizard.investment.attributes

    if @investment_wizard.valid?
      next_step = wizard_investment_next_step(current_step)
      create and return unless next_step
      if current_step == "review"
        redirect_to investments_path
      else 
        redirect_to action: next_step
      end
    else
      render current_step
    end

  end

  # Investment status 0 > active, 1 > draft, 2 > ended, 3 > payment
  #
  # If investment already exists in database,
  # then update all attributes with new values
  # else save new investment and generate all payout dates
  # redirect to ready_wizard otherwise redirect with error
  def create
    hash = {}
    if @investment_wizard.investment.id.present?
      invs = Investment.find(@investment_wizard.investment.id)
      @investment_wizard.investment.attributes.each do |attr|
        hash.merge!(attr[0].to_sym => attr[1] ) unless attr[0].in? ['id','created_at','updated_at']
      end

      hash.merge!(:status => 3) # change sttus to wait for payment
      invs.update_attributes(hash)

      generate_payouts(@investment_wizard.investment)

      session[:investment_attributes] = nil
      redirect_to pay_wizard_investment_path(investment: invs.id), notice: "Investment successfully updated"
    else
      if @investment_wizard.investment.save

        generate_payouts(@investment_wizard.investment)

        # Queue job to wait untill finish and change status
        InvestmentStatusCheckJob.set(wait_until: @investment_wizard.investment.end_date + 5.minutes).perform_later(@investment_wizard.investment.id)

        session[:investment_attributes] = nil
        @investment_wizard.investment.update_attributes(:status => 3) # change sttus to wait for payment
        redirect_to pay_wizard_investment_path(investment: @investment_wizard.investment.id), notice: "Investment successfully created"
      else
        redirect_to({action: Wizard::Investment::STEPS.first}, alert: "There were a problem when creating a investment.")
      end
    end

  end

  # Redirect here to continue of saved in draft investment
  # Redirect here to continue of add fund pressed
  def continue
    if params[:add_fund].present?
      session[:investment_attributes] = Investment.find(params[:add_fund]).attributes
      redirect_to amount_wizard_investment_path
    else
      session[:investment_attributes] = Investment.find(params[:draft]).attributes
      redirect_to plan_wizard_investment_path
    end
  end

  # Last step of investment wizard
  def ready
    @investment = Investment.where(user_id: current_user.id).last
  end

  def pay
    begin
      @investment = Investment.find(params[:investment])
    rescue StandardError => e
      redirect_to investments_path, alert: "Error: #{e}"
    end
    #amount = fiat_rate('usd',@investment.payment_method.ticker,@investment.invested_amount)
    #@amount_in_crypto = amount
  end

  # If clicked cancel button, save all values in database
  # skip_validation = true - to be able to skip validations
  # for empty attributes
  def cancel
    investment = Investment.new(session[:investment_attributes])
    investment.skip_validation = true
    investment.status = 1
    if investment.save
      redirect_to investments_path, notice: "Your Investments successfuly saved!"
    else
      redirect_to start_wizard_investment_path, alert: "Something went wrong, your investments hasn't been saved"
    end
  end

  def return_expected_return_value
    expected_return = ExpectedReturn.new(
      @investment_wizard.investment.attributes,
      @investment_wizard.investment.payout_frequency.name,
      current_user
    )
    @investment_wizard.investment.write_attribute("expected_return",expected_return.amount)
  end

  private

  def load_investment_wizard
    @investment_wizard = wizard_investment_for_step(action_name)
  end

  def wizard_investment_next_step(step)
    Wizard::Investment::STEPS[Wizard::Investment::STEPS.index(step) + 1]
  end

  def wizard_investment_for_step(step)
    raise InvalidStep unless step.in?(Wizard::Investment::STEPS)
    "Wizard::Investment::#{step.camelize}".constantize.new(session[:investment_attributes])
  end

  def set_investment_plans
    @investment_plans = InvestmentPlan.all
  end

  def set_payout_frequency
    @payout_frequency = PayoutFrequency.all
  end

  def set_payment_method
    @payment_method = PaymentMethod.all
  end

  def investment_wizard_params
    params.require(:investment_wizard).permit(
      :investment_plan_id, :name, :invested_amount, :status, :open_date, :end_date,
      :user_id, :timeframe, :payout_frequency_id, :payment_method_id, :expected_return,
      :currency
    )
  end

  def amount_incurrency(amount)
    rate = Currency::Converter.new(@currency,'usd').get_rate
    amount * rate
  end

  def set_earnings_weekly_percentage
    #@earnings_weekly_percentage = EarningPercentage.where(name: "weekly").first
  end

  def generate_payouts(investment)

    case investment.payout_frequency.name
    when "weekly"
      PayoutGenerator.new(investment).generate_weekly_payouts
      #ExpectedReturn.new(investment.attributes, investment.payout_frequency.name, current_user).payout_weekly
    when "twice"
      PayoutGenerator.new(investment).generate_twice_payouts
      #ExpectedReturn.new(investment.attributes, investment.payout_frequency.name, current_user).payout_twice
    when "monthly"
      PayoutGenerator.new(investment).generate_monthly_payouts
      #ExpectedReturn.new(investment.attributes, investment.payout_frequency.name, current_user).payout_monthly
    when "end_of_period"
      PayoutGenerator.new(investment).generate_end_of_period_payouts
      #ExpectedReturn.new(investment.attributes, investment.payout_frequency.name, current_user).payout_end_of_period
    end
  end

  class InvalidStep < StandardError; end
end

app/views/wizard_investments/amount.html.erb
<div class="inv-wiz">
<div class="container-fluid  min-100  d-flex flex-col">
  <div class="row flex-grow-1 bg-light investment_wizard_steps">

    <div class="col-md-9 p-4 flex-grow-1">
      <div class="back"><%= link_to fa_icon("arrow-left", text: "Back"), payout_wizard_investment_path %> </div>

      <div class="main_block">
        <header><h4>How much can you invest?</h4><h6>See how much your coins grow</h6></header>

        <%= form_for @investment_wizard, as: :investment_wizard, url: validate_step_wizard_investment_path do |form| %>
          <%= hidden_field_tag :current_step, 'amount' %>

          <% @investment_wizard.errors.full_messages.each do |error| %>
            <div class="form-group">
              <p style="color:red"><%= error %></p>
            </div>
          <% end %>

          <style>
          .input-group:before {
              z-index: 99;
              position: absolute;
              left: 15px;
              top: 5px;
              color: #777;
              font-size: 140%;
              content: '<%= @cur_sign[@currency] %>';
          }
          #investment_wizard_invested_amount {
            padding-left: 30px;
            }
          .input-group .fiat:after {
            z-index: 99;
              position: absolute;
              right: 10px;
              top: 5px;
              color: #777;
              font-size: 140%;
              content: '<%= @currency %>';
          }
          </style>

          <div class="form-row input-group">
            <div class="col-md-12 mb-6">
              <div class="form-group">
                <div class='fiat'>
                  <%= form.text_field :invested_amount, class: "form-control", autocomplete: "off" %>
                  <%#= form.text_field :invested_amount, class: "form-control fiat", value: "1000", aria: { :label => "Amount (to the nearest dollar)"}, autocomplete: "off" %>
                </div>
              </div>
            </div>
            <div class="col-md-12 mb-6">
              <select class="custom-select mr-sm-2" id="crypto_rate" >
              </select>
            </div>
          </div>

          <div class="card expected_return" style="margin-left: 0;">
            <div class="card-body">
              <h3 class="card-title" id="expected_return">0</h3>
              <p class="card-text">Expected Return<p>
            </div>
          </div>

          <script>
            window.earnings_weekly_percentage = '<%#= @earnings_weekly_percentage.percentage %>';
            //window.invPlan = '<%#= @investment_wizard.investment.investment_plan.title %>';
            window.investment_attributes = '<%= @investment_wizard.investment.attributes.map {|k,v| "investment[#{k}]=#{v}" }.split(',').join("&") %>';
            window.cur_sign = '<%= @cur_sign[@currency] %>';
          </script>

          <div class="form-group center" style="clear:both">
            <%= form.submit "Continue", class: "btn btn-primary btn-submit", id: "continueButton" %>
          </div>
        <% end %>
      </div>

    </div>

    <div class="col-md-3 p-4 flex-grow-1 wizard_sidebar" >

      <div class="cancel">
        <button type="button"  data-toggle="modal" data-target="#exampleModal">
          <%= fa_icon "close" %>
        </button>
      </div>

      <h4>Investment Summary</h4>
      <div class="steps_selected">
        <ul>
          <%#<li>%>
            <!--<p><%#= fa_icon "check" %> Investment Plan</p>-->
            <!--<p class="selected"><%#= @investment_wizard.investment.investment_plan.title %> <%#= @investment_wizard.investment.investment_plan.subtitle %></p>-->
          <%#</li>%>
          <li>
            <p><%= fa_icon "check" %> Investment Name</p>
            <p class="selected"><%= @investment_wizard.investment.name %></p>
          </li>
          <li>
            <p><%= fa_icon "check" %> TimeFrame</p>
            <p class="selected"><%= @investment_wizard.investment.timeframe_months %></p>
          </li>
          <li>
            <p><%= fa_icon "check" %> PayoutFrequency</p>
            <p class="selected"><%= @investment_wizard.investment.payout_frequency.title %></p>
          </li>
        </ul>
      </div>
    </div>

  </div>
</div>

<%= render "cancel_modal" %>

<!-- Modal -->
<div class="modal fade" id="changePlan" tabindex="-1" role="dialog" aria-labelledby="changePlanLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Investment Plan</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Your Invested amount has exceed the current plan, do you wish to upgrade your plan?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">No</button>
        <%= link_to "Yes", plan_wizard_investment_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>
</div>

app/views/wizard_investments/payout.html.erb
<div class="inv-wiz">
<div class="container-fluid  min-100  d-flex flex-col">
  <div class="row flex-grow-1 bg-light investment_wizard_steps">

    <div class="col-md-9 p-4 flex-grow-1">
      <div class="back"><%= link_to fa_icon("arrow-left", text: "Back"), timeframe_wizard_investment_path %> </div>

      <div class="main_block">
        <header><h4>Payout Frequency</h4><h6>This option will tell us how often you want us to transfer the collected coins to your account</h6></header>

        <%= form_for @investment_wizard, as: :investment_wizard, url: validate_step_wizard_investment_path do |form| %>
          <%= hidden_field_tag :current_step, 'payout' %>
          <%= form.hidden_field :payout_frequency_id, id: "radio_value" %>

          <% @investment_wizard.errors.full_messages.each do |error| %>
            <div class="form-group">
              <p style="color:red"><%= error %></p>
            </div>
          <% end %>

          <div class="card-group radio-group">
            <% @payout_frequency.each do |item| %>
              <!-- <%= item.title %> -->
              <div class="col-sm-6">
                <div class="card radio" data-value="<%= item.id %>">
                  <div class="card-content">
                    <div class="card-title">
                      <h3><%= item.title %></h3>
                    </div>
                    <h4><%= item.subtitle %></h4>
                    <%= sanitize item.description %>
                    <div class="card-footer">
                      <%= item.promo %>
                    </div>
                  </div>
                </div>
              </div>
            <% end %>

          </div><!-- /radio_group -->

          <div class="form-group center" style="clear:both">
            <%= form.submit "Continue", class: "btn btn-primary btn-submit" %>
          </div>
        <% end %>
      </div>

    </div>

    <div class="col-md-3 p-4 flex-grow-1 wizard_sidebar" >

      <div class="cancel">
        <button type="button"  data-toggle="modal" data-target="#exampleModal">
          <%= fa_icon "close" %>
        </button>
      </div>

      <h4>Investment Summary</h4>
      <div class="steps_selected">
        <ul>
          <%#<li>%>
            <!--<p><%#= fa_icon "check" %> Investment Plan</p>-->
            <!--<p class="selected"><%#= @investment_wizard.investment.investment_plan.title %> <%#= @investment_wizard.investment.investment_plan.subtitle %></p>-->
          <%#</li>%>
          <li>
            <p><%= fa_icon "check" %> Investment Name</p>
            <p class="selected"><%= @investment_wizard.investment.name %></p>
          </li>
          <li>
            <p><%= fa_icon "check" %> TimeFrame</p>
            <p class="selected"><%= @investment_wizard.investment.timeframe_months %></p>
          </li>
        </ul>
      </div>
    </div>

  </div>
</div>

<%= render "cancel_modal" %>
</div>

app/views/wizard_investments/review.html.erb
<div class="inv-wiz">
<div class="container-fluid  min-100  d-flex flex-col">
  <div class="row flex-grow-1 bg-light investment_wizard_steps">

    <div class="col p-4 flex-grow-1">
      <div class="back"><%= link_to fa_icon("arrow-left", text: "Back"), payment_wizard_investment_path %> </div>
      <div class="cancel">
        <button type="button"  data-toggle="modal" data-target="#exampleModal">
          <%= fa_icon "close" %>
        </button>
      </div>

      <div class="main_block">
        <header><h4>A few things to double-check</h4></header>

        <%= form_for @investment_wizard, as: :investment_wizard, url: validate_step_wizard_investment_path do |form| %>
          <%= hidden_field_tag :current_step, 'review' %>
          <%= form.hidden_field :payment_method_id, id: "radio_value" %>
          <%= form.hidden_field :user_id, value: current_user.id %>

          <% @investment_wizard.errors.full_messages.each do |error| %>
            <div class="form-group">
              <p style="color:red"><%= error %></p>
            </div>
          <% end %>


          <div class="card-group radio-group">
          <style>
          /* hardcoded, will be updated on layoyt styling */
          .card { height: 150px; }
          </style>
            <!-- investment plan -->
            <!-- Investment Name -->
            <div class="col-sm-6">
              <div class="card radio" data-value="<%= name_wizard_investment_path %>">
                <div class="card-content">
                  <div class="card-title">
                    <div class="steps_selected">
                      <ul>
                        <li>
                          <p><%= fa_icon "check" %> Investment Name</p>
                          <p><strong><%= @investment_wizard.investment.name %></strong></p>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- TimeFrame -->
            <div class="col-sm-6">
              <div class="card radio" data-value="<%= timeframe_wizard_investment_path %>">
                <div class="card-content">
                  <div class="card-title">
                    <div class="steps_selected">
                      <ul>
                        <li>
                          <p><%= fa_icon "check" %> TimeFrame</p>
                          <p><strong><%= @investment_wizard.investment.timeframe_months %></strong></p>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- Payout Frequency -->
            <div class="col-sm-6">
              <div class="card radio" data-value="<%= payout_wizard_investment_path %>">
                <div class="card-content">
                  <div class="card-title">
                    <div class="steps_selected">
                      <ul>
                        <li>
                          <p><%= fa_icon "check" %> Payout Frequency</p>
                          <p><strong><%= @investment_wizard.investment.payout_frequency.title %></strong></p>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- Initial Deposit -->
            <div class="col-sm-6">
              <div class="card radio" data-value="<%= amount_wizard_investment_path %>">
                <div class="card-content">
                  <div class="card-title">
                    <div class="steps_selected">
                      <ul>
                        <li>
                          <p><%= fa_icon "check" %> Initial Deposit</p>
                          <p><strong><%= @cur_sign[@currency] %> <%= @investment_wizard.investment.invested_amount %></strong></p>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- Expected Return -->
            <div class="col-sm-6">
              <div class="card radio" data-value="investment_plan" style="background: blue; color: white;">
                <div class="card-content">
                  <div class="card-title">
                    <h3 style="color:white"><%= @cur_sign[@currency] %> <%= @investment_wizard.investment.investment_earning %></h4>
                    <p>Expected Return</p>
                  </div>
                </div>
              </div>
            </div>

          </div><!-- /radio_group -->


          <div class="form-group center" style="clear:both">
            <%= link_to "Edit", plan_wizard_investment_path, class: "btn btn-primary btn-submit", id: "edit_btn", data: { path: plan_wizard_investment_path } %>
            <%= form.submit "Confirm", class: "btn btn-primary btn-submit" %>
          </div>
        <% end %>
      </div>

    </div>


  </div>
</div>

<%= render "cancel_modal" %>
</div>

app/views/wizard_investments/start.html.erb
<div class="inv-wiz">
<div class="container-fluid min-100 d-flex">
	<div class="row flex-grow-1 bg-light investment_wizard_steps">

    <div class="col p-4">

      <div class="back"><%= link_to fa_icon("arrow-left", text: "Back"), dashboards_path %> </div>
      <div class="cancel">
        <button type="button"  data-toggle="modal" data-target="#exampleModal">
          <%= fa_icon "close" %>
        </button>
      </div>

      <div class="center">
        <%= fa_icon "picture-o", style: "font-size:20rem" %>
      </div>

      <div class="main_block">
      <header>
        <h3>Setup your investment in 4 simple steps with Coinmitted!</h3>
        <h6>It’s never been so easy to setup a new investment, in just 3 minutes, we’ll put your coins to work harder for you. Enjoy the freedom of take care of yourself.</h6>
      </header>

      </div>
      <div class="center">
        <%= link_to "Get started", name_wizard_investment_path, class: "btn btn-primary btn-submit" %>
      </div>
    </div>

  </div>
</div>

<%= render "cancel_modal" %>
</div>

app/views/wizard_investments/timeframe.html.erb
<div class="inv-wiz">
<div class="container-fluid  min-100  d-flex flex-col">
  <div class="row flex-grow-1 bg-light investment_wizard_steps">

    <div class="col-md-9 p-4 flex-grow-1">
      <div class="back"><%= link_to fa_icon("arrow-left", text: "Back"), name_wizard_investment_path %> </div>

      <div class="main_block">
        <header><h4>Investment Timeframe</h4><h6>The Longer the better</h6></header>

        <%= form_for @investment_wizard, as: :investment_wizard, url: validate_step_wizard_investment_path do |form| %>
          <%= hidden_field_tag :current_step, 'timeframe' %>

          <% @investment_wizard.errors.full_messages.each do |error| %>
            <div class="form-group">
              <p style="color:red"><%= error %></p>
            </div>
          <% end %>

          <div >
            <h4 id="timeframe_value">3 Months</h4>
          </div>

          <div class="form-group" style="margin-top: 30px;">
            <%#<input type="range" style="width:100%" class="form-control-range" id="bSlider" min="1" max="10" value="3" onchange="timeframe(value)">%>
          <input type="range" id="bSlider" class="span2" value="" style="width:100%"
                                           data-slider-min="1"
                                           data-slider-max="12"
                                           data-slider-step="1"
                                           data-slider-value="3"
                                           data-slider-orientation="horizontal"
                                           data-slider-selection="after"
                                           data-slider-tooltip="show">
          </div>


          <%= form.hidden_field :open_date, value: Time.now %>
          <%= form.hidden_field :end_date, value: Time.now.months_since(3) %>
          <%= form.hidden_field :timeframe, value: 3 %>

          <!--
          <input type="text" id="bSlider" class="span2" value="" style="width:80%"
                                           data-slider-min="1"
                                           data-slider-max="10"
                                           data-slider-step="1"
                                           data-slider-value="3"
                                           data-slider-orientation="horizontal"
                                           data-slider-selection="after"
                                           data-slider-tooltip="show">
          -->
                  <script>
                  </script>

          <div class="form-group center" style="clear:both">
            <%= form.submit "Continue", class: "btn btn-primary btn-submit" %>
          </div>
        <% end %>
      </div>

    </div>

    <div class="col-md-3 p-4 flex-grow-1 wizard_sidebar" >

      <div class="cancel">
        <button type="button"  data-toggle="modal" data-target="#exampleModal">
          <%= fa_icon "close" %>
        </button>
      </div>

      <h4>Investment Summary</h4>
      <div class="steps_selected">
        <ul>
          <%#<li>%>
            <!--<p><%#= fa_icon "check" %> Investment Plan</p>-->
            <!--<p class="selected"><%#= @investment_wizard.investment.investment_plan.title %> <%#= @investment_wizard.investment.investment_plan.subtitle %></p>-->
          <%#</li>%>
          <li>
            <p><%= fa_icon "check" %> Investment Name</p>
            <p class="selected"><%= @investment_wizard.investment.name %></p>
          </li>
        </ul>
      </div>
    </div>

  </div>
</div>

<%= render "cancel_modal" %>
</div>