config/routes.rb
Rails.application.routes.draw do

  # New way user registration
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "(/:user)/sign_up/(:affiliate)" => "users/registrations#new", as: "new_user_registration"
    get "/:id/sign_out" => "devise/sessions#destroy"
  end


  authenticated :user, ->(u) { u.role == 'admin' } do
    root to: "users/visits#index", as: :admin_root
    namespace :users do
      resources :visits
    end
  end

  get "admin/week_percentages", to: 'admin#week_percentages', as: 'admin_week_percentages'
  get "admin/index", to: 'admin#index', as: 'admin_index'

  # for affiliates investors dashboard
  namespace :users do
    resources :users_investments, except: [:edit, :update]
    resources :affiliates
    resources :campaigns
  end

  # New way user registrations
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users do
    resources :investmentss
    resources :wallets
    get 'wallets/show'
  end

  resources :wallets, only: [:show] do
    resources :transactions, only: [:new, :create, :destroy]
    resources :users do
      resources :transactions, only: [:new, :create, :destroy]
    end
  end

  resources :transactions, only: [:index, :edit, :update, :show]
  resources :deposits, only: [:index, :edit, :update, :show]
  post "preset_investment", to: "investments#preset_investment", as: :preset_investment
  resources :investments do
    resources :payouts, only: [:index]
  end

  # Investment create
  post "investment/get_end_date", to: "investments#get_end_date"
  post "investment/get_frequency", to: "investments#get_frequency"
  post "investment/expected_return", to: "investments#expected_return"
  post "investment/get_range", to: "investments#get_range"
  post "investment/get_payment_method_id", to: "investments#get_payment_method_id"
  post "investment/confirm", to: "investments#confirm"
  post "investment/get_edit_investment", to: "investments#get_edit_investment"
  post "investment/get_frequency_title", to: "investments#get_frequency_title"
  post "investment/get_status", to: "investments#get_status"

  get :certificate, to: "investments#certificate"
  resources :week_percentages
  resources :payouts, only: [:index, :show]

  resources :dashboards, only: [:index]

  resources :performance, ohly: [:index]
  post "performance/chartdata", to: "performance#chartdata"
  # Admin user profile update
  get "profile/:id/edit", to: "profiles#edit", as: :edit_user_profile
  patch "profiles/:id", to: "profiles#update", as: :update_user_profile
  post "profiles/:id", to: "profiles#update"
  put "profiles/:id", to: "profiles#update"
  post "profile/password_update/:id", to: "profiles#password_update", as: :password_update_user_profile
  #put "profile/password_update/:id", to: "profiles#password_update", as: :password_update_user_profile

  get "support", to: "profiles#edit", as: :contact_support
  get "free_coins", to: "profile#edit", as: :free_coins

  # Profiles
  get "profile/edit", to: "profiles#edit", as: :edit_profile
  get 'profile/auth_factor', to: "profiles#auth_factor", as: :auth_factor
  get 'profile/enable_two_factor', to: "profiles#enable_two_factor", as: :enable_two_factor
  get 'profile/resend_otp', to: "profiles#resend_otp", as: :resend_otp

  # Phone Verification
  post "profile/send_phone_verification", to: "profiles#send_phone_verification"
  post "profile/verify_phone", to: "profiles#verify_phone"
  post "profile/resend_code", to: "profiles#send_phone_verification"
  #patch "profile/update", to: "profiles#update", as: :update_profile
  get "profiles", to: "profiles#index", as: :proifles
  post "profile/update", to: "profiles#update", as: :update_profile
  post "profile/password_update", to: "profiles#password_update", as: :password_update_profile
  delete "profile", to: "profiles#destroy", as: :profile_destroy

  # Phone Numbers
  resources :phone_numbers, only: [:create, :destroy]
  resources :number_verifications, only: [:new, :create]

  # admin user add phone number
  post "phone_numbers/:id", to: "phone_numbers#create", as: :user_phone_number
  delete "phone_numners", to: "phone_numbers#destory", as: :destroy_user_phone_number

  # Payments
  get 'payments_all', to: "payments#index", as: :payments_all
  get "payment/:id/show", to: "payments#show", as: :payment_show
  get 'payments', to: "payments#create"
  get 'payments/:id/address/:coin', to: "payments#address", as: :payment_address
  get 'payment/:id/status', to: "payments#status", as: :payment_status
  post 'payment/:id/callback', to: "payments#callback", as: :payment_callback
  post 'payments/:id/callback', to: "payments#callback", as: :payments_callback

  # routes for ajax calls
  match 'expected_return', to: "expected_return#earning", as: :expected_return, via: :post
  match 'expected_return_25', to: "expected_return#per_month_25", as: :expected_return_25, via: :post
  match 'currency_converter', to: "currency_converter#convert", as: :currency_converter, via: :get
  match 'currency_in_crypto', to: "currency_converter#show_crypto", as: :currency_in_crypto, via: :get

  # Wizard Investment
  resource :investment do
    get :name
    get :timeframe
    post :validate_step
  end
  resource :wizard_investment do
    get :start
    get :plan
    get :name
    get :timeframe
    get :payout
    get :amount
    get :payment
    get :review
    get :pay
    get :cancel
    get :ready
    get :continue
    get :return_expected_return_value

    post :validate_step
  end

  root 'dashboards#index'

  # APIs
  mount API::Base, at: '/'
  mount GrapeSwaggerRails::Engine, at: '/documentation'
end

app/models/payment.rb
require "open-uri"

class Payment < ApplicationRecord
  belongs_to :investment

  #after_create :set_currency
  after_update :update_success

  PAYBEAR_SECRET = Rails.application.credentials.paybear_secret
  DOMAIN = Rails.application.credentials.domain

  def get_address(coin)
    callback_url = CGI.escape("#{DOMAIN}/payments/#{id}/callback")
    url = "https://api.paybear.io/v2/#{coin.downcase}/payment/#{callback_url}?token=#{PAYBEAR_SECRET}"
    api_resp     = api_call(url)

    update(coin: coin)
    update(invoice: api_resp["data"]["invoice"])
    api_resp["data"]["address"]
    #{error: nil, address: api_resp["data"]["address"]}
  end

  def get_currency(ticker, fiat_rate, get_address = false)
    rate = get_rate(ticker)
    #rate = get_fiat_rate(fiat, ticker)

    if rate
      fiat_value = investment.invested_amount.to_f
      coins_value = (fiat_value / rate).round(8)

      ticker = ticker.downcase
      currencies = get_currencies
      if currencies[ticker]
        currency = currencies[ticker]
        currency[:coinsValue] = coins_value
        if get_address
          currency[:address] = get_address(ticker)
        else
          currency[:currencyUrl] = "/payments/#{id}/address/#{ticker}"
        end
        currency
      end
    end

    #Rails.logger.tagged("PAYMENT") do
      #Rails.logger.debug "------------currency updateing #{currency.to_json}"
    #end
    update(currencies: currency.to_json)
  end

  def fiat_rate(from, to)
   get_fiat_rate(from,to)
  end

  private

  def api_call(url)
    resp = ActiveSupport::JSON.decode(open(url).read)
    raise unless resp["success"]

    resp
  end


  def get_currencies
    $currencies ||= nil

    if $currencies.nil?
      url = "https://api.paybear.io/v2/currencies?token=#{PAYBEAR_SECRET}"
      response = ActiveSupport::JSON.decode(open(url).read)

      if response['success']
        $currencies = response['data']
      end
    end
    $currencies
  end

  def set_currencies
    api_resp  = api_call("https://api.paybear.io/v2/currencies?token=#{PAYBEAR_SECRET}")
    rates     = get_rates
    responses = api_resp["data"].map do |coin, response|
      response["coinsValue"]  = (investment.invested_amount / rates[coin]["mid"]).round(8)
      response["currencyUrl"] = "/payments/#{id}/address/#{coin}"
      response
    end

    #update(currencies: responses.to_json)
  end

  def get_fiat_rate(fiat, ticker)
    fiat = fiat.downcase
    ticker = ticker.downcase
    url = "https://api.paybear.io/v2/exchange/#{fiat}/rate"
    response = ActiveSupport::JSON.decode(open(url).read)
    if response['success']
      rates = response['data']
    end

    rates[ticker] ? rates[ticker]['mid'] : nil
  end

  def get_rate(cur_code)
    rates = get_rates
    cur_code = cur_code.downcase

    rates[cur_code] ? rates[cur_code]['mid'] : nil
  end

  def get_rates
    $rates ||= nil

    if $rates.nil?
      url = 'https://api.paybear.io/v2/exchange/usd/rate'
      response = ActiveSupport::JSON.decode(open(url).read)

      if response['success']
        $rates = response['data']
      end
    end
    $rates
  end

  def update_success
    return unless max_confirmations && confirmations && (confirmations >= max_confirmations) && (success.nil?)

    update(success: true)
  end
end

app/controllers/api/v1/payments.rb
module API
  module V1
    class Payments < Grape::API
      include API::V1::Defaults

      resource :payments do

        desc 'Create payment API', headers: Base.headers_definition
        post '/', root: :payments do
          authenticate!
          investment = Investment.find_by id: params[:investment_id]
          payment = Payment.create(investment: investment)
          ticker = investment.payment_method.ticker
          #fiat_rate = get_rate("USD", @investment.currency.upcase)
          fiat_rate = Currency::Converter.new('USD', investment.currency.upcase).get_rate
          payment.get_currency(ticker, fiat_rate, true)
          converted_amount = investment.invested_amount.to_f / fiat_rate

          response = {
              currencies:  [JSON.parse(payment.currencies)],
              fiatValue:   converted_amount,
              statusUrl:   "/api/v1/payments/#{payment.id}/status"
          }
          render response
        end

        desc 'Get payment status', headers: Base.headers_definition
        get '/:id/status', root: :payments do
          authenticate!
          payment = Payment.find_by(id: params[:id])
          response = {
              success:       payment.success,
              confirmations: payment.confirmations
          }
          render json: response
        end
      end
    end
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  include ApplicationHelper

  #skip_before_action :require_login,             only: [:callback]
  skip_before_action :verify_authenticity_token, only: [:callback]
  before_action      :set_investment,            only: [:create]
  before_action      :set_payment,               only: [:address, :status, :callback]
  before_action      :check_ownership,           only: [:address, :status]
  before_action :authenticate_user!, only: [:index, :show]
  before_action :superadmin?, only: [:index, :show]

  def index
    @payments = Payment.all
  end

  def show
    @payment = Payment.find(params[:id])
  end

  def create
    @payment = Payment.create(investment: @investment)


    ticker = @investment.payment_method.ticker
    #fiat_rate = get_rate("USD", @investment.currency.upcase)
    fiat_rate = Currency::Converter.new('USD', @investment.currency.upcase).get_rate
    @payment.get_currency(ticker, fiat_rate, true)
    converted_amount = @investment.invested_amount.to_f / fiat_rate

    response = {
      currencies:  [JSON.parse(@payment.currencies)],
      fiatValue:   converted_amount,
      onBackClick: investments_path,
      redirectTo:  "/",
      statusUrl:   "/payment/#{@payment.id}/status"
    }

    render json: response
  end

  def address
    response = @payment.get_address(params.require(:coin))
    render json: response
  end

  def status
    response = {
      success:       @payment.success,
      confirmations: @payment.confirmations
    }

    render json: response
  end

  def callback

    Rails.logger.tagged("PAYMENT") do
      Rails.logger.debug params
    end

    if params[:confirmations]
      head :unauthorized unless @payment.invoice == params.require(:invoice)
      data = params
      #invoice = data[:invoice]
      #@payment = Payment.where(invoice: invoice).first

      @payment.update(max_confirmations: params.require(:maxConfirmations))
      @payment.update(confirmations:     params.require(:confirmations))

      if data[:confirmations] >= data[:maxConfirmations]
        #in_transaction = params.require(:inTransaction)
        amount_paid = data[:inTransaction][:amount].to_f / 10**data[:inTransaction][:exp].to_f

        @payment.update(coins_received: amount_paid)
        @payment.investment.update_attributes(status: 0)

        Rails.logger.tagged("CALLBACK PAYMENT") do
          Rails.logger.debug "Investor: #{Investor}"
        end
        # Investor (User wallet)
        investor = @payment.investment.user
        investor.wallet.currencies.each do |item|
          if item.ticker.upcase == @payment.coin.upcase
            new_amount = item.amount + amount_paid
            item.update(amount: new_amount)
          end
        end

        Rails.logger.tagged("ADD CRYPTO TO USER WALLET") do
          Rails.logger.debug "Currencies: #{investor.wallet.currencies.inspect}"
        end

        render plain: @payment.invoice
      else
        render plain: 'waiting for confirmations'
      end
    #else
      #render plain: 'error'
    end
  end

  private

  def set_investment
    @investment = Investment.find(params.require(:investment))
    head :unauthorized unless @investment.user == current_user
  end

  def set_payment
    @payment = Payment.find(params.require(:id))
  end

  def check_ownership
    head :unauthorized unless @payment.investment.user == current_user
  end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/callback.html.erb
<h1>Payments#callback</h1>
<p>Find me in app/views/payments/callback.html.erb</p>

app/views/payments/create.html.erb
<h1>Payments#create</h1>
<p>Find me in app/views/payments/create.html.erb</p>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<%= render "layouts/header" %>
<div class="container-fluid">
  <div class="row">

    <%= render 'layouts/sidebar' %>
     <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

        <h1>Payments</h1>

        <table class="table" id="data">
          <thead>
            <tr>
              <th>Success</th>
              <th>Investment ID</th>
              <th>Invoice</th>
              <th>Confirmations</th>
              <th>Max Confirmations</th>
              <th>Coin</th>
              <th>Coins received</th>
              <th></th>
              <th></th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @payments.each do |payment| %>
              <tr>
                <td>
                  <%= fa_icon "circle", style: payment.success == true ? "color:lightgreen" : "color:red" %>
                </td>
                <td><%= payment.investment.id %></td>
                <td><%= payment.invoice %></td>
                <td><%= payment.confirmations %></td>
                <td><%= payment.max_confirmations %></td>
                <td><%= payment.coin %></td>
                <td><%= payment.coins_received %></td>
                <td><%= link_to 'Show', payment_show_path(payment) %></td>
                <td><%#= link_to 'Edit', edit_payment_path(payment) %></td>
                <td><%#= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>

        <br>

        <%#= link_to 'New Payment', new_payment_path %>

  </div>
</div>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<%= render "layouts/header" %>
<div class="container-fluid">
  <div class="row">

    <%= render 'layouts/sidebar' %>
     <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

       <div class="jumbotron text-center">
         <h2>Payments</h2>
       </div>

       <p><strong>Payment <%= @payment.success ? "successful" : "unsuccessful" %></strong>
         <%= fa_icon "circle", style: @payment.success == true ? "color:lightgreen" : "color:red" %>
       </p>

        <p>
          <strong>Investment Name:</strong>
          <%= @payment.investment.name %>
        </p>

        <p>
          <strong>Invoince:</strong>
          <%= @payment.invoice %>
        </p>

        <p>
          <strong>Confirmations:</strong>
          <%= @payment.confirmations %>
        </p>
        <p>
          <strong>Max Confirmations:</strong>
          <%= @payment.max_confirmations %>
        </p>

        <p>
          <strong>Coin:</strong>
          <%= @payment.coin %>
        </p>

        <p>
          <strong>Coins Received:</strong>
          <%= @payment.coins_received %>
        </p>
        <p>
          <strong>Currency:</strong>
          <div class="form-group">
            <textarea class="form-control" style="height: 250px"><%= @payment.currencies %></textarea>
          </div>
        </p>

      <%= link_to 'Back', payments_all_path, class: "btn btn-primary" %>

  </div>
</div>

app/views/payments/status.html.erb
<h1>Payments#status</h1>
<p>Find me in app/views/payments/status.html.erb</p>