config/routes.rb
Rails.application.routes.draw do

  # New way user registration
  devise_scope :user do
    get "/sign_in" => "devise/sessions#new"
    get "(/:user)/sign_up/(:affiliate)" => "users/registrations#new", as: "new_user_registration"
    get "/:id/sign_out" => "devise/sessions#destroy"
  end


  authenticated :user, ->(u) { u.role == 'admin' } do
    root to: "users/visits#index", as: :admin_root
    namespace :users do
      resources :visits
    end
  end

  get "admin/week_percentages", to: 'admin#week_percentages', as: 'admin_week_percentages'
  get "admin/index", to: 'admin#index', as: 'admin_index'

  # for affiliates investors dashboard
  namespace :users do
    resources :users_investments, except: [:edit, :update]
    resources :affiliates
    resources :campaigns
  end

  # New way user registrations
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }

  resources :users do
    resources :investmentss
    resources :wallets
    get 'wallets/show'
  end

  resources :wallets, only: [:show] do
    resources :transactions, only: [:new, :create, :destroy]
    resources :users do
      resources :transactions, only: [:new, :create, :destroy]
    end
  end

  resources :transactions, only: [:index, :edit, :update, :show]
  resources :deposits, only: [:index, :edit, :update, :show]
  post "preset_investment", to: "investments#preset_investment", as: :preset_investment
  resources :investments do
    resources :payouts, only: [:index]
  end

  # Investment create
  post "investment/get_end_date", to: "investments#get_end_date"
  post "investment/get_frequency", to: "investments#get_frequency"
  post "investment/expected_return", to: "investments#expected_return"
  post "investment/get_range", to: "investments#get_range"
  post "investment/get_payment_method_id", to: "investments#get_payment_method_id"
  post "investment/confirm", to: "investments#confirm"
  post "investment/get_edit_investment", to: "investments#get_edit_investment"
  post "investment/get_frequency_title", to: "investments#get_frequency_title"
  post "investment/get_status", to: "investments#get_status"

  get :certificate, to: "investments#certificate"
  resources :week_percentages
  resources :payouts, only: [:index, :show]

  resources :dashboards, only: [:index]

  resources :performance, ohly: [:index]
  post "performance/chartdata", to: "performance#chartdata"
  # Admin user profile update
  get "profile/:id/edit", to: "profiles#edit", as: :edit_user_profile
  patch "profiles/:id", to: "profiles#update", as: :update_user_profile
  post "profiles/:id", to: "profiles#update"
  put "profiles/:id", to: "profiles#update"
  post "profile/password_update/:id", to: "profiles#password_update", as: :password_update_user_profile
  #put "profile/password_update/:id", to: "profiles#password_update", as: :password_update_user_profile

  get "support", to: "profiles#edit", as: :contact_support
  get "free_coins", to: "profile#edit", as: :free_coins

  # Profiles
  get "profile/edit", to: "profiles#edit", as: :edit_profile
  get 'profile/auth_factor', to: "profiles#auth_factor", as: :auth_factor
  get 'profile/enable_two_factor', to: "profiles#enable_two_factor", as: :enable_two_factor
  get 'profile/resend_otp', to: "profiles#resend_otp", as: :resend_otp

  # Phone Verification
  post "profile/send_phone_verification", to: "profiles#send_phone_verification"
  post "profile/verify_phone", to: "profiles#verify_phone"
  post "profile/resend_code", to: "profiles#send_phone_verification"
  #patch "profile/update", to: "profiles#update", as: :update_profile
  get "profiles", to: "profiles#index", as: :proifles
  post "profile/update", to: "profiles#update", as: :update_profile
  post "profile/password_update", to: "profiles#password_update", as: :password_update_profile
  delete "profile", to: "profiles#destroy", as: :profile_destroy

  # Phone Numbers
  resources :phone_numbers, only: [:create, :destroy]
  resources :number_verifications, only: [:new, :create]

  # admin user add phone number
  post "phone_numbers/:id", to: "phone_numbers#create", as: :user_phone_number
  delete "phone_numners", to: "phone_numbers#destory", as: :destroy_user_phone_number

  # Payments
  get 'payments_all', to: "payments#index", as: :payments_all
  get "payment/:id/show", to: "payments#show", as: :payment_show
  get 'payments', to: "payments#create"
  get 'payments/:id/address/:coin', to: "payments#address", as: :payment_address
  get 'payment/:id/status', to: "payments#status", as: :payment_status
  post 'payment/:id/callback', to: "payments#callback", as: :payment_callback
  post 'payments/:id/callback', to: "payments#callback", as: :payments_callback

  # routes for ajax calls
  match 'expected_return', to: "expected_return#earning", as: :expected_return, via: :post
  match 'expected_return_25', to: "expected_return#per_month_25", as: :expected_return_25, via: :post
  match 'currency_converter', to: "currency_converter#convert", as: :currency_converter, via: :get
  match 'currency_in_crypto', to: "currency_converter#show_crypto", as: :currency_in_crypto, via: :get

  # Wizard Investment
  resource :investment do
    get :name
    get :timeframe
    post :validate_step
  end
  resource :wizard_investment do
    get :start
    get :plan
    get :name
    get :timeframe
    get :payout
    get :amount
    get :payment
    get :review
    get :pay
    get :cancel
    get :ready
    get :continue
    get :return_expected_return_value

    post :validate_step
  end

  root 'dashboards#index'

  # APIs
  mount API::Base, at: '/'
  mount GrapeSwaggerRails::Engine, at: '/documentation'
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]
  before_action :set_currencies, only: [:new, :create, :edit]
  before_action :admin_role?, only: [:index, :edit, :update, :show]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions
  # POST /transactions.json
  def create
    unless edit_user? &&  current_user.wallet.id != params[:wallet_id]
      # TODO change later
      raise "error"
    end

    merged_data = {wallet_id: params[:wallet_id], name: "Withdraw to #{transaction_params[:ticker]}"}
    @transaction = Transaction.new(transaction_params.merge(merged_data))

    respond_to do |format|
      if enough_amount && @transaction.save
        format.html { redirect_to wallet_path(current_user), notice: 'Transaction was successfully created.' }
        #format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)

        dedact_from_user_wallet

        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to wallet_path(current_user.wallet.id), notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def enough_amount
    to_transfer = params[:transaction][:amount]
    current_user.wallet.currencies.each do |item|
      if item.ticker == params[:transaction][:ticker]
        return true if item.amount.to_f >= to_transfer.to_f
      end
    end
    false
  end

  def dedact_from_user_wallet
    @transaction.wallet.currencies.each do |item|
      if item.ticker == @transaction.ticker
        new_amount = item.amount.to_f - @transaction.amount.to_f
        item.update(amount: new_amount)
        binding.pry
      end
    end
    @transaction.update(flag: 1)
  end

    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      if edit_user?
        @transaction = Transaction.where(id: params[:id], wallet_id: params[:wallet_id]).first
      else
        @transaction = Transaction.where(id: params[:id], wallet_id: current_user.wallet.id).first
      end
    end

    def set_currencies
      cur_params = params[:wallet_id].present? ? { wallet_id: params[:wallet_id] } : { id: Transaction.find(params[:id]).wallet.id }
      @currecies = WalletCurrency.where(cur_params)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def transaction_params
      params.require(:transaction).permit(
        :name, :address, :amount, :ticker, :wallet_id
      )
      #params.fetch(:transaction, {})
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper

  def transaction_create_path(action, edit_user)
    if action == 'edit'
      @transaction
    elsif edit_user == true
      [:wallet, :user, @transaction]
    else
      [:wallet, @transaction]
    end
  end

end

app/views/transactions/_form.html.erb
  <%= form_with(model: transaction_create_path(action_name, edit_user?), local: true) do |form| %>
  <%#= form_with(model: action_name == 'edit' ? transaction : [:wallet, transaction], local: true) do |form| %>

  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label "Crypto-currency" %>
    <%= form.select :ticker, @currecies.map {|c| ["#{c.name} #{c.amount.to_f}", c.ticker] },{}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :amount %>
    <%= form.text_field :amount, pattern: "[0-9].*", class: "form-control", autocomplete: "off" %>
  </div>

  <div class="form-group">
    <%= form.label "to address" %>
    <%= form.text_field :address, class: "form-control", autocomplete: "off" %>
  </div>

  <div class="actions">
    <% if action_name == 'edit' %>
      <%= form.submit "Accept?", class: "btn btn-success" %>
      <%= link_to "Cancel", transactions_path, class: "btn btn-primary" %>
    <% else %>
      <%= form.submit "Send", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<%= render "layouts/header" %>
<div class="container-fluid">
  <div class="row">

    <%= render 'layouts/sidebar' %>

     <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
       <%= render "layouts/notifications" %>
        <h1>Editing Transaction</h1>

        <%= render 'form', transaction: @transaction %>

        <%#= link_to 'Show', @transaction %>
        <%#= link_to 'Cancel', transactions_path, class: "btn btn-primary" %>

     </main>
  </div>
</div>

app/views/transactions/index.html.erb
<%= render "layouts/header" %>
<div class="container-fluid">
  <div class="row">

    <%= render 'layouts/sidebar' %>

     <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
       <%= render "layouts/notifications" %>

          <h1>Withdrawal History</h1>

          <table class="table" id="data">
            <thead>
              <tr>
                <th></th>
                <th>User</th>
                <th>Amount</th>
                <th>From</th>
                <th>Date</th>
                <th>Status</th>
                <th>Address</th>
                <th></th>
                <th></th>
              </tr>
            </thead>

            <tbody>
              <% @transactions.each do |transaction| %>
                <tr>
                  <td>
                  <%= fa_icon "circle", style: transaction.flag == 'completed' ? "color:lightgreen" : "color:red" %>
                  </td>
                  <td><%= link_to transaction.wallet.user.profile.name, edit_user_profile_path(transaction.wallet.user.profile.id) %></td>
                  <td><%= transaction.amount.to_f %></td>
                  <td><%= transaction.ticker %></td>
                  <td><%= transaction.created_at.strftime("%d %B, %Y") %></td>
                  <td><%= transaction.flag %></td>
                  <td><%= transaction.address %></td>
                  <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
                  <td><%#= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <br>

          <%#= link_to 'New Transaction', new_transaction_path %>

     </main>
  </div>
</div>

app/views/transactions/new.html.erb
<%= render "layouts/header" %>
<div class="container-fluid">
  <div class="row">

    <%= render 'layouts/sidebar' %>

     <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

        <h1>New Transaction</h1>

        <%= render 'form', transaction: @transaction %>

     </main>
  </div>
</div>

app/views/transactions/show.html.erb
<%= render "layouts/header" %>
<div class="container-fluid">
  <div class="row">

    <%= render 'layouts/sidebar' %>

     <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
       <%= render "layouts/notifications" %>

       <div class="jumbotron text-center">
         <h2>Withdrawal</h2>
       </div>

       <p>Name: <%= @transaction.name %></p>
       <p>User: <%= link_to @transaction.wallet.user.profile.name, edit_user_profile_path(@transaction.wallet.user.profile.id) %></p>
       <p>Amount: <%= @transaction.amount %></p>
       <p>To Address: <%= @transaction.address %></p>

        <%= link_to 'Back', transactions_path %>

     </main>
  </div>
</div>